(()=>{
'use strict';
const V='2.4';
const q=(s,r=document)=>r.querySelector(s), qa=(s,r=document)=>Array.from(r.querySelectorAll(s));
const norm=s=>(s||'').replace(/\s+/g,' ').trim().toLowerCase();
const txt=e=>norm(e&&e.textContent);
const closestCard=e=>e&&e.closest('button,a,[role="button"],.card,.tile,.benefit,.action,.option,.item,.quick,.quick-card,.feature')||e?.parentElement;
const fire=(el,type='input')=>el&&el.dispatchEvent(new Event(type,{bubbles:true}));
const setInput=(el,val)=>{if(!el)return;const d=Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value');if(d&&d.set)d.set.call(el,String(val));else el.value=String(val);fire(el,'input');fire(el,'change');};
const ownTextElements=()=>qa('button,a,label,h1,h2,h3,h4,p,span,div,small,strong').filter(e=>e.children.length<4);
const findText=(needle)=>{const n=norm(needle);return ownTextElements().find(e=>txt(e).includes(n));};
const findLabelInput=(needle)=>{const n=norm(needle);for(const el of qa('label,.field,.form-row,.form-group,[class*="field-"],[class$="-field"]')){if(!txt(el).includes(n))continue;if(el.tagName==='LABEL'&&el.htmlFor){const linked=document.getElementById(el.htmlFor);if(linked?.matches('input,select'))return linked;}const i=q('input,select',el);if(i)return i;}const t=findText(needle);let p=t;for(let depth=0;p&&depth<5;depth++,p=p.parentElement){if(!txt(p).includes(n))continue;const i=q('input,select',p);if(i)return i;}return null;};
function ensureSheet(){if(q('#v24-sheet'))return;document.body.insertAdjacentHTML('beforeend',`<div id="v24-backdrop" class="v24-sheet-backdrop"></div><section id="v24-sheet" class="v24-sheet" role="dialog" aria-modal="true" aria-label="VAYQUO"><div class="v24-grab"></div><div id="v24-sheet-content"></div></section>`);q('#v24-backdrop').addEventListener('click',closeSheet);}
function openSheet(html){ensureSheet();q('#v24-sheet-content').innerHTML=html;q('#v24-backdrop').classList.add('is-open');q('#v24-sheet').classList.add('is-open');const c=q('.v24-close',q('#v24-sheet'));if(c)c.addEventListener('click',closeSheet);}
function closeSheet(){q('#v24-backdrop')?.classList.remove('is-open');q('#v24-sheet')?.classList.remove('is-open');}
window.VAYQUO_PARTNERS=window.VAYQUO_PARTNERS||{open(name,url){try{sessionStorage.setItem('vayquo:lastPartner',JSON.stringify({name,url,at:Date.now()}));}catch{}window.open(url,'_blank','noopener,noreferrer');}};
function help(title,body){openSheet(`<div class="v24-sheet-head"><div><div class="v24-sheet-kicker">Kurz erklärt</div><h3>${title}</h3></div><button class="v24-close" aria-label="Schließen">×</button></div><p>${body}</p>`);}
const helpMap=[
 ['barpreis des gleichen fluges','Barpreis','Der normale Preis desselben Fluges. VAYQUO braucht ihn nur für den Vergleich: So siehst du, ob deine Punkte gegenüber Barzahlung wirklich einen guten Gegenwert liefern.'],
 ['prämienpreis im programm','Prämienpreis','So viele Punkte oder Meilen verlangt das jeweilige Programm für diesen Flug. Sobald Live-Daten angebunden sind, soll VAYQUO diesen Wert möglichst automatisch übernehmen.'],
 ['steuern & gebühren','Steuern & Gebühren','Der Geldbetrag, der bei einer Prämienbuchung zusätzlich zu den Punkten anfällt. Er wird beim echten Punktewert mitgerechnet.'],
 ['im programm schon vorhanden','Bereits vorhandene Punkte','Punkte oder Meilen, die du im Zielprogramm bereits hast. VAYQUO berücksichtigt sie, bevor es einen Transfer aus deinem Kartenprogramm empfiehlt.'],
 ['dein mindestwert','Dein Mindestwert','Deine persönliche Untergrenze pro Punkt. VAYQUO warnt dich, wenn ein Einsatz darunter liegt.']
];
function addHelp(){for(const [needle,title,body] of helpMap){const el=findText(needle);if(!el||el.dataset.v24Help)continue;const b=document.createElement('button');b.type='button';b.className='v24-help';b.textContent='?';b.setAttribute('aria-label',`${title} erklären`);b.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();help(title,body);});el.appendChild(b);el.dataset.v24Help='1';}}
function extractRoute(){const s=document.body.innerText||'';let m=s.match(/\b([A-Z]{3})\s*[→>-]\s*([A-Z]{3})\b/);return m?`${m[1]} → ${m[2]}`:'Deinen Flug';}
function currentFlightValues(){const cash=findLabelInput('barpreis des gleichen fluges');const points=findLabelInput('prämienpreis im programm');const fees=findLabelInput('steuern & gebühren');return{cash:cash?.value||'',points:points?.value||'',fees:fees?.value||'',cashEl:cash,pointsEl:points,feesEl:fees};}
function fmtEuro(v){const n=String(v).replace(/[^0-9,.-]/g,'').replace('.','').replace(',','.');const x=Number(n);return Number.isFinite(x)&&x?new Intl.NumberFormat('de-DE',{style:'currency',currency:'EUR',maximumFractionDigits:0}).format(x):'Preis folgt';}
function fmtPoints(v){const n=Number(String(v).replace(/\D/g,''));return n?new Intl.NumberFormat('de-DE').format(n)+' P':'Punkte folgen';}
function enhanceFlight(){const cash=findLabelInput('barpreis des gleichen fluges');if(!cash||q('#v24-flight-shell'))return;const container=cash.closest('.field,.input,.form-row,.form-group')||cash.parentElement?.parentElement||cash.parentElement;if(!container)return;const vals=currentFlightValues();const route=extractRoute();const shell=document.createElement('section');shell.id='v24-flight-shell';shell.className='v24-flight-shell';shell.innerHTML=`<div class="v24-flight-head"><div><div class="v24-flight-kicker">Einfacher auswählen</div><div class="v24-flight-title">${route}</div><div class="v24-flight-note">Wähle zuerst den Flug. Die Vergleichswerte werden danach automatisch übernommen.</div></div><span class="v24-demo-pill">TESTDATEN</span></div><div class="v24-flight-actions"><button type="button" class="v24-primary" id="v24-show-flights">Flüge anzeigen</button><button type="button" class="v24-secondary" id="v24-scan-flight">Screenshot nutzen</button></div><input id="v24-flight-file" type="file" accept="image/*" hidden><div class="v24-scan-status" id="v24-scan-status"></div><div class="v24-flight-list" id="v24-flight-list"><button type="button" class="v24-flight-row" id="v24-current-flight"><span class="v24-flight-logo">VQ</span><span class="v24-flight-main"><span class="v24-flight-name">Aktueller Flug aus deinem Test</span><span class="v24-flight-meta">${route} · vorhandene VAYQUO-Daten</span></span><span class="v24-flight-price"><b>${fmtEuro(vals.cash)}</b>${fmtPoints(vals.points)} + ${fmtEuro(vals.fees)}</span></button><div class="v24-flight-row" style="cursor:default;opacity:.58"><span class="v24-flight-logo">•••</span><span class="v24-flight-main"><span class="v24-flight-name">Weitere Flüge</span><span class="v24-flight-meta">kommen automatisch mit der Live-Flugsuche</span></span></div></div><details class="v24-fallback" id="v24-manual"><summary>Werte manuell ändern</summary></details>`;
container.parentNode.insertBefore(shell,container);
const details=q('#v24-manual',shell);const manualInputs=[findLabelInput('barpreis des gleichen fluges'),findLabelInput('prämienpreis im programm'),findLabelInput('steuern & gebühren'),findLabelInput('im programm schon vorhanden')];const manualBlocks=[];for(const input of manualInputs){const block=input?.closest('.field,.input,.form-row,.form-group')||input?.parentElement?.parentElement||input?.parentElement;if(block&&!manualBlocks.includes(block))manualBlocks.push(block);}for(const block of manualBlocks)details.appendChild(block);
q('#v24-show-flights',shell).addEventListener('click',()=>q('#v24-flight-list',shell).classList.toggle('is-open'));
q('#v24-current-flight',shell).addEventListener('click',()=>{q('#v24-current-flight',shell).classList.add('is-selected');q('#v24-flight-list',shell).classList.remove('is-open');details.open=false;const t=q('#v24-scan-status',shell);t.textContent='Flug ausgewählt. Barpreis, Punktepreis und Gebühren wurden aus dem aktuellen Testdatensatz übernommen.';t.classList.add('is-visible');});
q('#v24-scan-flight',shell).addEventListener('click',()=>q('#v24-flight-file',shell).click());
q('#v24-flight-file',shell).addEventListener('change',e=>{const f=e.target.files?.[0];if(!f)return;const t=q('#v24-scan-status',shell);t.textContent=`${f.name} ausgewählt. Der Scan-Flow ist vorbereitet; automatisches Auslesen folgt mit der OCR/API-Anbindung. Bis dahin kannst du die Werte unter „manuell ändern“ ergänzen.`;t.classList.add('is-visible');});
}
function sheetHead(kicker,title,copy){return `<div class="v24-sheet-head"><div><div class="v24-sheet-kicker">${kicker}</div><h3>${title}</h3></div><button class="v24-close" aria-label="Schließen">×</button></div><p>${copy}</p>`;}
function openSixt(){openSheet(sheetHead('Unterwegs','SIXT ride','Plane deinen Transfer direkt aus VAYQUO. Später werden hinterlegte Karten- und Statusvorteile automatisch dagegen geprüft.')+`<label class="v24-field"><span>Abholung</span><input id="v24-sixt-from" placeholder="z. B. Flughafen DUS"></label><label class="v24-field"><span>Ziel</span><input id="v24-sixt-to" placeholder="Hotel oder Adresse"></label><div class="v24-grid2"><label class="v24-field"><span>Datum</span><input id="v24-sixt-date" type="date"></label><label class="v24-field"><span>Uhrzeit</span><input id="v24-sixt-time" type="time"></label></div><button class="v24-primary v24-wide" id="v24-sixt-check">Fahrt planen</button><div class="v24-result" id="v24-sixt-result"><strong>Transfer ist vorbereitet.</strong><small>VAYQUO prüft in der finalen Version vor dem Absprung deinen passenden Karten-/Statusvorteil. Der externe Button läuft bereits über die zentrale Partner-Link-Schicht.</small><button class="v24-secondary v24-wide" id="v24-sixt-open">Zu SIXT ride</button></div><p class="v24-mini">Noch ohne Live-Preis/API – der Bedienablauf ist jetzt aber anklickbar und vollständig durchgängig.</p>`);q('#v24-sixt-check').addEventListener('click',()=>q('#v24-sixt-result').classList.add('is-visible'));q('#v24-sixt-open').addEventListener('click',()=>window.VAYQUO_PARTNERS.open('sixt-ride','https://www.sixt.com/ride/'));}
function openLounges(){openSheet(sheetHead('Reisevorteil','Lounges','Gib Flughafen und optional Terminal ein. VAYQUO führt den Zugang später mit deinen hinterlegten Karten und Programmen zusammen.')+`<div class="v24-grid2"><label class="v24-field"><span>Flughafen</span><input id="v24-lounge-airport" maxlength="3" placeholder="DUS"></label><label class="v24-field"><span>Terminal</span><input id="v24-lounge-terminal" placeholder="optional"></label></div><button class="v24-primary v24-wide" id="v24-lounge-check">Lounges prüfen</button><div class="v24-result" id="v24-lounge-result"><strong id="v24-lounge-title">Zugang wird geprüft</strong><small id="v24-lounge-copy">In dieser Testversion ist der echte Flow vorhanden. Live-Loungedaten, Öffnungszeiten und Gastregeln werden im Daten-Schritt angebunden und dann gegen deine Programme geprüft.</small></div><p class="v24-mini">Keine erfundenen Lounge-Daten: Solange keine Live-Quelle angebunden ist, zeigt VAYQUO bewusst keine vermeintlich aktuellen Ergebnisse.</p>`);q('#v24-lounge-check').addEventListener('click',()=>{const a=(q('#v24-lounge-airport').value||'deinem Flughafen').toUpperCase();q('#v24-lounge-title').textContent=`Lounges für ${a}`;q('#v24-lounge-result').classList.add('is-visible');});}
function openRestaurants(){openSheet(sheetHead('Vor Ort','Restaurant Finder','Finde Restaurants passend zu deinem Standort. Kartenvorteile und Partnerangebote sollen später automatisch priorisiert werden.')+`<label class="v24-field"><span>Ort</span><input id="v24-rest-place" placeholder="z. B. Palma oder Berlin"></label><button class="v24-primary v24-wide" id="v24-rest-check">Restaurants finden</button><div class="v24-result" id="v24-rest-result"><strong>Suche vorbereitet.</strong><small>Live-Partner- und Kartendaten sind noch nicht angebunden. Du kannst die Kartensuche schon öffnen; VAYQUO wird später nur relevante Vorteile darüberlegen.</small><button class="v24-secondary v24-wide" id="v24-rest-open">Auf Karte öffnen</button></div><p class="v24-mini">Externe Links laufen zentral über die VAYQUO-Partner-Schicht, damit Affiliate-/Tracking-Partner später ohne Umbau ergänzt werden können.</p>`);q('#v24-rest-check').addEventListener('click',()=>q('#v24-rest-result').classList.add('is-visible'));q('#v24-rest-open').addEventListener('click',()=>{const p=q('#v24-rest-place').value.trim();const url='https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p?`restaurants ${p}`:'restaurants near me');window.VAYQUO_PARTNERS.open('restaurant-map',url);});}
function bindFeature(needles,handler,key){for(const n of needles){const el=findText(n);if(!el)continue;const c=closestCard(el);if(!c||c.dataset[`v24${key}`])continue;c.classList.add('v24-clickable');c.dataset[`v24${key}`]='1';c.addEventListener('click',ev=>{if(ev.target.closest('.v24-help'))return;ev.preventDefault();ev.stopPropagation();handler();},true);}}
function compactHome(){const t=norm(document.body.innerText);const isHome=(t.includes('nicht einfach punkte haben')||t.includes('das maximum daraus machen'))&&t.includes('deine programme');document.body.classList.toggle('v24-home',isHome);if(!isHome)return;for(const el of qa('main p,main .sub,main .muted,main small')){const s=norm(el.textContent);if(s.length>90&&!el.closest('#v24-flight-shell,.v24-sheet')&&!el.dataset.v24Compact){el.classList.add('v24-home-copy');el.title=el.textContent.trim();el.dataset.v24Compact='1';}}for(const el of qa('main section,main .card,main .block')){if(!el.dataset.v24Tight){el.classList.add('v24-home-section');el.dataset.v24Tight='1';}}}
function init(){addHelp();enhanceFlight();bindFeature(['sixt ride'],openSixt,'Sixt');bindFeature(['restaurant finder','restaurants'],openRestaurants,'Restaurants');bindFeature(['lounges','lounge finder'],openLounges,'Lounges');compactHome();}
window.openSixt=openSixt;window.openRestaurants=openRestaurants;window.openLounges=openLounges;
let scheduled=false;const schedule=()=>{if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;try{init();}catch(e){console.warn('VAYQUO v2.4 enhancement',e);}});};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',schedule,{once:true});else schedule();
new MutationObserver(schedule).observe(document.documentElement,{subtree:true,childList:true});
console.info(`VAYQUO enhancement layer v${V}`);
})();
