const fs=require('fs');const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('assets/vayquo-machine.js','utf8');
const css=fs.readFileSync('assets/vayquo-machine.css','utf8');
const analytics=fs.readFileSync('v36-anonymous-analytics.js','utf8');
const partner=fs.readFileSync('partner.html','utf8');
const partnerJs=fs.readFileSync('assets/vayquo-partner.js','utf8');
const pv=fs.readFileSync('photovoltaik/index.html','utf8');
const pvCost=fs.readFileSync('photovoltaik/kosten.html','utf8');
const pvStorage=fs.readFileSync('photovoltaik/speicher.html','utf8');
const pvEeg=fs.readFileSync('photovoltaik/einspeiseverguetung.html','utf8');
const pvPaderborn=fs.readFileSync('photovoltaik/paderborn.html','utf8');
const seoCss=fs.readFileSync('assets/vayquo-seo.css','utf8');
const sitemap=fs.readFileSync('sitemap.xml','utf8');
for(const id of ['top','vqStart','vqWizard','vqQuestionScreen','vqQuestion','vqOptions','vqPostcodeScreen','vqPostcodeForm','vqPostcode','vqResultScreen','vqProfileSummary','vqCheckProviders','vqContactScreen','vqContactForm','vqFirstName','vqEmail','vqPhone','vqConsent','vqSubmit','vqSuccess']) assert(html.includes(`id="${id}"`),`missing #${id}`);
for(const project of ['pv','heating','kitchen','bath']) assert(html.includes(`data-project="${project}"`),`missing project ${project}`);
assert(html.includes('Einmal anfragen.<br>Passende Angebote bekommen.<br>Fertig.'),'one-request consumer USP missing');
assert(html.includes('1 ANFRAGE · BIS ZU 3 PASSENDE ANGEBOTE'),'supporting USP line missing');
for(const trust of ['Kostenlos','Unverbindlich','Max. 3 Anbieter','Keine Telefonlawine']) assert(html.includes(trust),`trust signal missing: ${trust}`);
assert((html.match(/images\.unsplash\.com/g)||[]).length>=4,'project photography missing');
assert(html.includes('Kontaktdaten fragen wir erst, nachdem du deine Angebotsvorschau gesehen hast.'),'offer-preview-before-contact promise missing');
assert(html.includes('DEINE ANGEBOTSVORSCHAU'),'offer preview heading missing');
assert(html.includes('Bis zu 3 Angebote anfordern'),'offer CTA missing');
assert(html.includes('Noch kein verbindlicher Preis'),'transparent non-fake pricing disclosure missing');
assert(html.includes('Vorname <em>optional</em>'),'first name must be optional in the low-friction contact step');
assert(html.indexOf('id="vqEmail"')<html.indexOf('id="vqPhone"'),'email must be requested before phone');
assert(html.includes('bis zu 3 passende Fachbetriebe'),'consumer sharing consent missing');
for(const banned of ['Eine Plattform · zwei Wege','Qualifizierte Projekte statt Adressverkauf','Komplette Setups statt Einzelprodukte','PROJEKTPLATTFORM','Projekt-Engine']) assert(!html.includes(banned),`consumer homepage still exposes business-model copy: ${banned}`);
assert(!html.includes('data-project="workshop"'),'workshop must not clutter high-ticket launch screen');
assert(!html.includes('data-project="gym"'),'gym must not clutter high-ticket launch screen');
assert(css.includes('height:100svh'),'homepage must behave like an app viewport');
assert(css.includes('overflow:hidden'),'homepage must avoid info-scroll behavior');
assert(css.includes('.vq-trustbar'),'trust bar styling missing');
assert(css.includes('background-image:var(--photo)'),'image-led project cards missing');
assert(css.includes('.vq-profile-card'),'project profile value reveal styling missing');
assert(css.includes('.vq-offer-preview'),'offer preview styling missing');
assert(js.includes("const PROJECTS={"),'project question engine missing');
for(const project of ['pv:{label:','heating:{label:','kitchen:{label:','bath:{label:']) assert(js.includes(project),`question config missing ${project}`);
assert(js.includes('function showPostcode()'),'postcode-before-contact step missing');
assert(js.includes('function showResult()'),'offer preview value reveal missing');
assert(js.includes("$('#vqCheckProviders').addEventListener('click'"),'offer request gate missing');
assert(js.includes("first_name:$('#vqFirstName').value.trim()||null"),'optional first name persistence missing');
assert(js.includes('async function submitRequest'),'qualified request submission missing');
assert(js.includes('vayquo_project_requests'),'project request database endpoint missing');
assert(js.includes("consent_share:true"),'explicit share consent persistence missing');
assert(js.includes("emit('revenue_request_success')"),'successful lead conversion event missing');
assert(js.includes("get('project')"),'SEO landing pages must deep-link directly into the requested funnel');
assert(js.includes('function marketingAttribution()'),'lead attribution engine missing');
for(const key of ['utm_source','utm_medium','utm_campaign','utm_term','utm_content','gclid','msclkid','landing_path']) assert(js.includes(key),`marketing attribution missing ${key}`);
assert(js.includes('marketing_attribution:marketingAttribution()'),'lead request must persist marketing attribution');
for(const event of ['revenue_intent','revenue_flow_start','revenue_result','revenue_primary_click','revenue_request_success']) assert(analytics.includes(event),`analytics missing ${event}`);
assert(partner.includes('id="partnerForm"'),'separate provider acquisition page missing');
assert(partner.includes('So sieht eine VAYQUO-Anfrage aus.'),'partner must see concrete lead value before signup');
assert(partner.includes('49 € / Anfrage'),'pilot economics must be visible to providers');
assert(partnerJs.includes('vayquo_partner_interest'),'partner database endpoint missing');
assert(pv.includes('PV planen, ohne fünfmal alles zu erklären.'),'PV hub value proposition missing');
assert(pv.includes('?project=pv&source='),'PV hub must deep-link into PV funnel');
assert(pv.includes('speicher.html'),'PV hub must link storage intent page');
assert(pv.includes('einspeiseverguetung.html'),'PV hub must link EEG intent page');
assert(pvCost.includes('Was kostet Photovoltaik 2026?'),'high-intent PV cost page missing');
assert(pvCost.includes('6.500–14.000 €'),'current PV cost orientation missing');
assert(pvStorage.includes('Was kostet ein PV-Speicher 2026?'),'high-intent PV storage page missing');
assert(pvStorage.includes('300–700 €/kWh'),'current storage price orientation missing');
assert(pvStorage.includes('verbraucherzentrale.de'),'storage source missing');
assert(pvEeg.includes('PV-Einspeisevergütung 2026?'),'high-intent EEG page missing');
assert(pvEeg.includes('7,70 ct/kWh'),'current household EEG rate missing');
assert(pvEeg.includes('bundesnetzagentur.de'),'official EEG source missing');
assert(pvPaderborn.includes('Photovoltaik in Paderborn'),'useful local PV page missing');
assert(pvPaderborn.includes('Solarkataster'),'local Paderborn value missing');
assert(seoCss.includes('.seo-hero'),'PV SEO design system missing');
for(const url of ['https://vayquo.de/photovoltaik/','https://vayquo.de/photovoltaik/kosten.html','https://vayquo.de/photovoltaik/speicher.html','https://vayquo.de/photovoltaik/einspeiseverguetung.html','https://vayquo.de/photovoltaik/paderborn.html','https://vayquo.de/partner.html']) assert(sitemap.includes(url),`sitemap missing ${url}`);
assert(!sitemap.includes('/setups/'),'old affiliate setup pages must not remain in growth sitemap');
console.log('VAYQUO one-request + PV growth engine contract: OK');
