const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const html=read('index.html');
const js=read('assets/vayquo-machine.js');
const css=read('assets/vayquo-machine.css');
const smartJs=read('assets/vayquo-smart-result.js');
const smartCss=read('assets/vayquo-smart-result.css');
const analytics=read('v36-anonymous-analytics.js');
const legal=read('rechtliches.html');
const partner=read('partner.html');
const partnerJs=read('assets/vayquo-partner.js');
const portal=read('partner-portal.html');
const portalJs=read('assets/vayquo-portal.js');
const customer=read('kunde.html');
const customerJs=read('assets/vayquo-customer.js');
const customerCss=read('assets/vayquo-customer.css');
const pv=read('photovoltaik/index.html');
const pvCost=read('photovoltaik/kosten.html');
const pvStorage=read('photovoltaik/speicher.html');
const pvEeg=read('photovoltaik/einspeiseverguetung.html');
const pvLocal=read('photovoltaik/paderborn.html');
const heating=read('heizung/index.html');
const kitchen=read('kueche/index.html');
const bath=read('bad/index.html');
const about=read('ueber-vayquo.html');
const sitemap=read('sitemap.xml');
const robots=read('robots.txt');
const readme=read('README.md');

for(const id of ['vqStart','vqWizard','vqQuestionScreen','vqPostcodeScreen','vqResultScreen','vqProfileSummary','vqOfferLabel','vqEstimatePrice','vqEstimateSecond','vqEstimateThird','vqCheckProviders','vqContactScreen','vqContactForm','vqConsent','vqSubmit','vqSuccess']) assert(html.includes(`id="${id}"`),`missing #${id}`);
for(const project of ['pv','heating','kitchen','bath']) assert(html.includes(`data-project="${project}"`),`missing project ${project}`);
assert(html.includes('Erst wissen, was realistisch ist.<br>Dann Angebote holen.'),'instant-check USP missing');
for(const phrase of ['Sofortergebnis','Keine Registrierung','Angebote optional']) assert(html.includes(phrase),`instant trust missing ${phrase}`);
for(const phrase of ['Preis- &amp; Anlagencheck','Eignungs- &amp; Kostencheck','Budget- &amp; Marktcheck','Kosten- &amp; Budgetcheck']) assert(html.includes(phrase),`category instant check missing ${phrase}`);
assert(html.includes('Passende Angebote dazu holen'),'provider matching must be optional after instant result');
assert(html.includes('Anonym passende Rückmeldungen starten.'),'provider matching must start anonymous');
assert(html.includes('Keine E-Mail. Keine Telefonnummer.'),'anonymous-first promise missing');
assert(!html.includes('id="vqEmail"')&&!html.includes('id="vqPhone"')&&!html.includes('id="vqFirstName"'),'main funnel must not collect contact data before provider selection');
assert(html.includes('bis zu 3 passenden Fachbetrieben'),'main consent must cap anonymous provider sharing');
assert(html.includes('vayquo-smart-result.js'),'deal-check layer must load after instant engine');
assert((html.match(/images\.unsplash\.com/g)||[]).length>=4,'project photography missing');
assert(css.includes('.vq-offer-preview'),'instant result card styling missing');
assert(smartCss.includes('.vq-smart-panel')&&smartCss.includes('.vq-smart-grid'),'deal-check styling missing');

for(const project of ['pv:{label:','heating:{label:','kitchen:{label:','bath:{label:']) assert(js.includes(project),`question config missing ${project}`);
for(const fn of ['function pvResult()','function heatingResult()','function kitchenResult()','function bathResult()','function instantResult()']) assert(js.includes(fn),`instant engine missing ${fn}`);
assert(js.includes("price='6,5–20 Tsd. €'"),'PV market corridor missing');
assert(js.includes("b:'29–62 Tsd. €*'"),'heating market-comparison value missing');
assert(js.includes("a:'Ø 12.404 €'"),'kitchen market benchmark missing');
assert(js.includes("'1,2–3,5 Tsd. €/m²'"),'bath market benchmark missing');
assert(js.includes('verbraucherzentrale'),'heating source disclosure missing');
assert(js.includes('1kuechen.de'),'kitchen source disclosure missing');
assert(js.includes('aroundhome.de'),'bath source disclosure missing');
assert(js.includes('first_name:null,email:null,phone:null'),'initial provider request must persist no contact PII');
assert(js.includes("CONSENT_VERSION='2026-09-02-v5'"),'anonymous-first consent version missing');
assert(js.includes('marketing_attribution:marketingAttribution()'),'lead attribution missing');
assert(js.includes('referrer_host'),'lead attribution must store only referrer host');
assert(!js.includes('referrer:(document.referrer'),'full referrer URL must not be persisted in project attribution');
for(const category of ['pv:{title:','heating:{title:','kitchen:{title:','bath:{title:']) assert(smartJs.includes(category),`deal-check guide missing ${category}`);
for(const concept of ['MUSS DRINSTEHEN','OFT VERGESSEN','SPÄTER VERGLEICHEN']) assert(smartJs.includes(concept),`deal-check concept missing ${concept}`);
for(const event of ['revenue_intent','revenue_flow_start','revenue_result','revenue_primary_click','revenue_request_success']) assert(analytics.includes(event),`analytics missing ${event}`);

assert(legal.includes('Vorname, E-Mail-Adresse und Telefonnummer werden in diesem Schritt nicht abgefragt'),'privacy copy must describe anonymous initial request');
assert(legal.includes('Erst wenn der Nutzer später eine konkrete Anbieter-Rückmeldung aktiv auswählt'),'privacy copy must describe contact-on-selection');
assert(legal.includes('höchstens drei'),'privacy copy must cap provider exposure/freigaben');
assert(legal.includes('EU-Region'),'privacy copy must disclose Supabase region class');

assert(partner.includes('PV · HEIZUNG · KÜCHE · BAD'),'partner page must sell all four categories');
for(const category of ['Photovoltaik','Heizung','Küche','Bad']) assert(partner.includes(`>${category}</label>`),`partner category missing ${category}`);
assert(partner.includes('49 € Pilotpreis je freigegebenem Kontakt'),'multi-category pilot economics missing');
assert(partnerJs.includes("source:'partner_page_multi_category_pilot'"),'partner source must be multi-category');

assert(portal.includes('noindex,nofollow'),'partner portal must remain private');
assert(portal.includes('STRUKTURIERTE RÜCKMELDUNGEN'),'partner portal must explain structured replies');
assert(portal.includes('Ein Konto allein gibt keinen Zugriff'),'portal must explain server-gated project access');
assert(portal.includes('Partnerkonto anlegen'),'partner signup action missing');
assert(portalJs.includes("client.rpc('vayquo_my_leads'"),'partner lead feed missing');
assert(portalJs.includes('RESPONSE_LABELS'),'category-specific provider response fields missing');
for(const field of ['data-primary','data-secondary','data-included','data-availability']) assert(portalJs.includes(field),`structured provider field missing ${field}`);
assert(portalJs.includes('Bitte mindestens eine Preisgrenze angeben.'),'provider response price requirement missing');
assert(portalJs.includes('Bitte Kernleistung, enthaltene Arbeiten und Verfügbarkeit ausfüllen.'),'provider response completeness requirement missing');
assert(portalJs.includes('p_details:details'),'structured provider details must persist through RPC');
assert(portalJs.includes('client.auth.signUp'),'partner account creation missing');
assert(!portalJs.includes('vayquo_partner_signup_eligible'),'public partner-email eligibility lookup must stay removed');

assert(customer.includes('noindex,nofollow'),'private customer comparison page must remain private');
assert(customer.includes('Nicht nur Preise.<br>Leistung vergleichen.'),'customer comparison value proposition missing');
assert(customer.includes('Kontakt erst bei Auswahl'),'customer page must promise delayed contact capture');
assert(customerJs.includes("client.rpc('vayquo_customer_matches'"),'customer comparison RPC missing');
assert(customerJs.includes('provider_details'),'customer must consume structured provider details');
assert(customerJs.includes('DETAIL_LABELS'),'customer category detail labels missing');
for(const field of ['primary_spec','secondary_spec','included','availability']) assert(customerJs.includes(field),`customer comparison field missing ${field}`);
for(const field of ['data-contact-email','data-contact-phone','data-contact-name','data-contact-consent']) assert(customerJs.includes(field),`contact-on-selection field missing ${field}`);
assert(customerJs.includes("client.rpc('vayquo_customer_select_partner'"),'customer selection RPC missing');
for(const arg of ['p_email:email','p_phone:phone','p_first_name:firstName||null']) assert(customerJs.includes(arg),`customer selection contact arg missing ${arg}`);
assert(customerCss.includes('.vc-details')&&customerCss.includes('.vc-contact-gate'),'structured comparison/contact gate styling missing');

assert(pv.includes('?project=pv&source='),'PV SEO funnel missing');
assert(pv.includes('anonymisiert'),'PV hub must describe anonymous provider phase');
assert(pvCost.includes('6.500–14.000 €')&&pvCost.includes('10.000–20.000 €'),'PV cost market ranges missing');
assert(pvStorage.includes('300–700 €/kWh'),'PV storage benchmark missing');
for(const value of ['8,10 ct/kWh','12,62 ct/kWh','7,06 ct/kWh','10,64 ct/kWh','5,84 ct/kWh']) assert(pvEeg.includes(value),`current EEG value missing ${value}`);
assert(pvEeg.includes('leistungsanteilig'),'EEG page must explain tiered calculation');
assert(pvLocal.includes('Solarkataster'),'local PV source context missing');
assert(heating.includes('?project=heating&source=seo-heizung'),'heating SEO funnel missing');
assert(heating.includes('Sofortergebnis'),'heating instant promise missing');
assert(kitchen.includes('?project=kitchen&source=seo-kueche'),'kitchen SEO funnel missing');
assert(kitchen.includes('12.404 €'),'kitchen benchmark missing');
assert(bath.includes('?project=bath&source=seo-bad'),'bath SEO funnel missing');
for(const value of ['1.200 €/m²','2.000 €/m²','3.500 €/m²']) assert(bath.includes(value),`bath market level missing ${value}`);
assert(bath.includes('aroundhome.de'),'bath current market source missing');

assert(about.includes('Photovoltaik')&&about.includes('Heizung')&&about.includes('Küche')&&about.includes('Bad'),'about page must describe current project categories');
assert(!about.includes('Membership Rewards')&&!about.includes('PAYBACK'),'about page must not describe old points product');
assert(readme.includes('Photovoltaik, Heizung, Küche und Bad'),'README must describe current product');
assert(!readme.includes('Home Gym')&&!readme.includes('Schrauber-Garage'),'README must not present legacy product as current');

for(const url of ['https://vayquo.de/','https://vayquo.de/photovoltaik/','https://vayquo.de/heizung/','https://vayquo.de/kueche/','https://vayquo.de/bad/','https://vayquo.de/partner.html','https://vayquo.de/ueber-vayquo.html']) assert(sitemap.includes(url),`sitemap missing ${url}`);
for(const legacy of ['/ratgeber/','/setups/','moment.html','pulse.html','beta.html','beta2.html','beta3.html']) assert(!sitemap.includes(legacy),`legacy URL must not be in sitemap: ${legacy}`);
assert(!sitemap.includes('partner-portal.html')&&!sitemap.includes('kunde.html'),'private portals must not be indexed');
assert(robots.includes('Disallow: /tests/'),'test directory should stay blocked');
assert(!robots.includes('beta.html'),'removed beta pages should not remain in robots rules');
for(const file of ['beta.html','beta2.html','beta3.html','moment.html','pulse.html','ratgeber/index.html','setups/index.html']) assert(!fs.existsSync(file),`legacy public page still exists: ${file}`);

console.log('VAYQUO current house-project product contract: OK');