const fs=require('fs');const assert=require('assert');
const html=fs.readFileSync('index.html','utf8');
const js=fs.readFileSync('assets/vayquo-machine.js','utf8');
const css=fs.readFileSync('assets/vayquo-machine.css','utf8');
const analytics=fs.readFileSync('v36-anonymous-analytics.js','utf8');
const partner=fs.readFileSync('partner.html','utf8');
const partnerJs=fs.readFileSync('assets/vayquo-partner.js','utf8');
const portal=fs.readFileSync('partner-portal.html','utf8');
const portalJs=fs.readFileSync('assets/vayquo-portal.js','utf8');
const pv=fs.readFileSync('photovoltaik/index.html','utf8');
const heating=fs.readFileSync('heizung/index.html','utf8');
const kitchen=fs.readFileSync('kueche/index.html','utf8');
const bath=fs.readFileSync('bad/index.html','utf8');
const sitemap=fs.readFileSync('sitemap.xml','utf8');
for(const id of ['vqStart','vqWizard','vqQuestionScreen','vqPostcodeScreen','vqResultScreen','vqProfileSummary','vqOfferLabel','vqEstimatePrice','vqEstimateSecond','vqEstimateThird','vqCheckProviders','vqContactScreen','vqContactForm','vqSuccess']) assert(html.includes(`id="${id}"`),`missing #${id}`);
for(const project of ['pv','heating','kitchen','bath']) assert(html.includes(`data-project="${project}"`),`missing project ${project}`);
assert(html.includes('Erst wissen, was realistisch ist.<br>Dann Angebote holen.'),'instant-check USP missing');
for(const phrase of ['Sofortergebnis','Keine Registrierung','Angebote optional']) assert(html.includes(phrase),`instant trust missing ${phrase}`);
for(const phrase of ['Preis- &amp; Anlagencheck','Eignungs- &amp; Kostencheck','Budget- &amp; Marktcheck','Kosten- &amp; Budgetcheck']) assert(html.includes(phrase),`category instant check missing ${phrase}`);
assert(html.indexOf('DEIN VAYQUO SOFORT-CHECK')<html.indexOf('NUR WENN DU ANGEBOTE WILLST'),'instant result must come before contact request');
assert(html.includes('Passende Angebote dazu holen'),'provider matching must be optional after instant result');
assert((html.match(/images\.unsplash\.com/g)||[]).length>=4,'project photography missing');
assert(css.includes('.vq-offer-preview'),'instant result card styling missing');
for(const project of ['pv:{label:','heating:{label:','kitchen:{label:','bath:{label:']) assert(js.includes(project),`question config missing ${project}`);
for(const fn of ['function pvResult()','function heatingResult()','function kitchenResult()','function bathResult()','function instantResult()']) assert(js.includes(fn),`instant engine missing ${fn}`);
assert(js.includes("a:'6,5–20 Tsd. €'")||js.includes("price='6,5–20 Tsd. €'"),'PV market corridor missing');
assert(js.includes("b:'29–62 Tsd. €*'"),'heating market-comparison value missing');
assert(js.includes("a:'Ø 12.404 €'"),'kitchen market benchmark missing');
assert(js.includes("'3–5 Tsd. €/m²'"),'bath market benchmark missing');
assert(js.includes('verbraucherzentrale'),'heating source disclosure missing');
assert(js.includes('1kuechen.de'),'kitchen source disclosure missing');
assert(js.includes('blauarbeit.de'),'bath source disclosure missing');
assert(js.includes('function showResult()'),'instant result reveal missing');
assert(js.includes("$('#vqCheckProviders').addEventListener('click'"),'optional provider gate missing');
assert(js.includes('marketing_attribution:marketingAttribution()'),'lead attribution missing');
for(const event of ['revenue_intent','revenue_flow_start','revenue_result','revenue_primary_click','revenue_request_success']) assert(analytics.includes(event),`analytics missing ${event}`);
assert(partner.includes('PV · HEIZUNG · KÜCHE · BAD'),'partner page must sell all four categories');
for(const category of ['Photovoltaik','Heizung','Küche','Bad']) assert(partner.includes(`>${category}</label>`),`partner category missing ${category}`);
assert(partner.includes('49 € Pilotpreis je freigegebenem Kontakt'),'multi-category pilot economics missing');
assert(partnerJs.includes("source:'partner_page_multi_category_pilot'"),'partner source must be multi-category');
assert(portal.includes('noindex,nofollow'),'partner portal must remain private');
assert(portalJs.includes("client.rpc('vayquo_my_leads'"),'partner lead feed missing');
assert(pv.includes('?project=pv&source='),'PV SEO funnel missing');
assert(heating.includes('?project=heating&source=seo-heizung'),'heating SEO funnel missing');
assert(heating.includes('Sofortergebnis'),'heating instant promise missing');
assert(kitchen.includes('?project=kitchen&source=seo-kueche'),'kitchen SEO funnel missing');
assert(kitchen.includes('12.404 €'),'kitchen benchmark missing');
assert(bath.includes('?project=bath&source=seo-bad'),'bath SEO funnel missing');
assert(bath.includes('3.000–5.000 €/m²'),'bath benchmark missing');
for(const url of ['https://vayquo.de/photovoltaik/','https://vayquo.de/heizung/','https://vayquo.de/kueche/','https://vayquo.de/bad/','https://vayquo.de/partner.html']) assert(sitemap.includes(url),`sitemap missing ${url}`);
assert(!sitemap.includes('partner-portal.html'),'private partner portal must not be indexed');
console.log('VAYQUO multi-category instant project-check contract: OK');